name: Supabase Keep Alive

on:
  schedule:
    # Every day 08:00 UTC
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  ping_supabase:
    runs-on: ubuntu-latest

    steps:
      - name: Get Repo
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: |
          pip install supabase

      - name: Run Script
        env:
          # GitHub Secrets keys
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

        run: python autorequest.py
